hashicorp/syntax

- .github/release.yml
- .github/workflows/release.yml
- RELEASE.md
This adds a GitHub Action that packages up the syntax files for consumption in other products. The action is triggered by a git tag matching the version strategy we use and automatically generates a changelog inside the release based on all pull requests since last. A release document was added explaining the process.
A release would be downloaded using a URL like: `https://github.com/hashicorp/syntax/releases/download/v0.2.3/terraform.tmGrammar.json`
An example release looks like this:
> Release Automation

- syntaxes/hcl.tmGrammar.json
- tests/snapshot/hcl/issue809.hcl
- tests/snapshot/hcl/issue809.hcl.snap
This PR adds the missing `:` operator for computed map keys. Until now the `end` regex wasn't able to match anything and claimed the rest of the file as `meta.mapping.key`.
Closes [#809](https://github.com/hashicorp/vscode-terraform/issues/809)
> Fix highlighting for computed map keys

- syntaxes/terraform.tmGrammar.json
- tests/snapshot/terraform/expressions_dynamic.tf.snap
- tests/snapshot/terraform/expressions_for.tf.snap
- tests/snapshot/terraform/expressions_functions.tf.snap
- tests/snapshot/terraform/expressions_splat.tf.snap
- tests/snapshot/terraform/expressions_strings.tf.snap
- tests/snapshot/terraform/issue927.tf.snap
- tests/snapshot/terraform/modules.tf.snap
- tests/snapshot/terraform/variables_input.tf.snap
- tests/snapshot/terraform/variables_local.tf.snap
This PR removes all cross-file include patterns from the Terraform grammar by duplicating the patterns from the HCL grammar. 
In an editor of your choice, one can view the Terraform-specific changes best by comparing `terraform.tmGrammar.json` and `hcl.tmGrammar.json`.
Closes #16
> Copy patterns from HCL grammar to Terraform grammar

- syntaxes/hcl.tmGrammar.json
- tests/snapshot/hcl/basic.hcl.snap
- tests/snapshot/hcl/expressions_conditional.hcl.snap
- tests/snapshot/hcl/expressions_for.hcl.snap
- tests/snapshot/hcl/expressions_functions.hcl.snap
- tests/snapshot/hcl/issue941.hcl.snap
- tests/snapshot/hcl/variables_input.hcl.snap
- tests/snapshot/hcl/variables_local.hcl.snap
This PR updates the scope for generic functions in HCL to be more in line with theme scopes.
Should be merged after #17 (this will fix the Terraform snapshot tests)
> Update scope for HCL function highlighting

- syntaxes/terraform.tmGrammar.json
- tests/snapshot/terraform/issue809.tf
- tests/snapshot/terraform/issue809.tf.snap
- tests/snapshot/terraform/issue941.tf
- tests/snapshot/terraform/issue941.tf.snap
I missed these two fixes from #8 and #9 while copying patterns from HCL to Terraform.
> Add missing grammar updates to Terraform

- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/issue19.hcl
- tests/snapshot/hcl/issue19.hcl.snap
- tests/snapshot/hcl/variables_input.hcl.snap
- tests/snapshot/terraform/issue19.tf
- tests/snapshot/terraform/issue19.tf.snap
- tests/snapshot/terraform/variables_input.tf.snap
This PR updates the HCL and the Terraform grammar to fix the highlighting of nested complex types.
Closes #19
> Fix highlighting of nested complex types

- package-lock.json
- package.json
Result of `npm version --no-git-tag-version v0.2.0`
> prepare release v0.2.0

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/basic.hcl.snap
- tests/snapshot/hcl/expressions_for.hcl.snap
- tests/snapshot/hcl/expressions_functions.hcl.snap
- tests/snapshot/hcl/expressions_strings.hcl.snap
- tests/snapshot/terraform/expressions_for.tf.snap
- tests/snapshot/terraform/expressions_functions.tf.snap
- tests/snapshot/terraform/expressions_strings.tf
- tests/snapshot/terraform/expressions_strings.tf.snap
Closes #31.
Tests output:
```
$ npm test
> syntax@0.2.0 test
> npm run test:snap
> syntax@0.2.0 test:snap
> npm run test:snap:hcl && npm run test:snap:sentinel && npm run test:snap:terraform
> syntax@0.2.0 test:snap:hcl
> npx vscode-tmgrammar-snap -s source.hcl -g syntaxes/hcl.tmGrammar.json -t "tests/snapshot/hcl/*.hcl"
✓ tests/snapshot/hcl/basic.hcl run successfully.
✓ tests/snapshot/hcl/blocks.hcl run successfully.
✓ tests/snapshot/hcl/comments.hcl run successfully.
✓ tests/snapshot/hcl/data_sources.hcl run successfully.
✓ tests/snapshot/hcl/expressions_conditional.hcl run successfully.
✓ tests/snapshot/hcl/expressions_dynamic.hcl run successfully.
✓ tests/snapshot/hcl/expressions_for.hcl run successfully.
Generating snapshot tests/snapshot/hcl/expressions_functions.hcl.snap
✓ …
```
> Variables with no space between them break syntax highlighting

- README.md
This updates the README to link to the newly-announced official HCL VS Code extension: https://www.hashicorp.com/blog/announcing-the-hcl-extension-for-visual-studio-code-0-1
> chore: add HCL VS Code extension link to README

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/expressions_splat.hcl
- tests/snapshot/hcl/expressions_splat.hcl.snap
- tests/snapshot/hcl/expressions_strings.hcl
- tests/snapshot/hcl/expressions_strings.hcl.snap
- tests/snapshot/hcl/expressions_traversals.hcl
- tests/snapshot/hcl/expressions_traversals.hcl.snap
- tests/snapshot/hcl/variables_local.hcl.snap
- tests/snapshot/terraform/expressions_splat.tf
- tests/snapshot/terraform/expressions_splat.tf.snap
- tests/snapshot/terraform/expressions_strings.tf
- tests/snapshot/terraform/expressions_strings.tf.snap
- tests/snapshot/terraform/expressions_traversals.hcl
- tests/snapshot/terraform/expressions_traversals.hcl.snap
- tests/snapshot/terraform/variables_local.tf.snap
Fixes https://github.com/hashicorp/syntax/issues/40
After I started looking more closely at the existing tests I realised there is a few more bugs beyond what's described in #40
This fixes handling of the following expressions:
- legacy numeric indexes (`attribute.0`)
- legacy splat syntax (`attribute.*`)
- square brackets around splat syntax (`attribute[*]`)
The PR is best reviewed commit-by-commit, especially because I updated some of the test data to make them more accurate, as per https://github.com/hashicorp/syntax/pull/43#discussion_r889980319
**HCL**
**Terraform**
> Fix highlighting of `.0`, `.*` attribute access and `[*]` brackets

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/issue1286.hcl
- tests/snapshot/hcl/issue1286.hcl.snap
This PR improves the attribute name matching in two ways:
* We now match a whole word with the negative lookahead instead of just the first letter
* We only match `null`, `false`, and `true` when they are followed by whitespace, so words like `nullable` are matched correctly.
Fixes https://github.com/hashicorp/vscode-terraform/issues/1286
> Improve attribute name matching

- builder/go.mod
This aims to resolve the large diff problem exhibited in the following dependabot PRs by bumping the Go version and running `go mod tidy`:
- https://github.com/hashicorp/syntax/pull/53
- https://github.com/hashicorp/syntax/pull/54
Admittedly I don't know what the real root cause is, but bumping the version and running `go mod tidy` generally should never do harm, so I thought why I not do that. 🤷🏻 
--- 
For context, with the existing `go.mod`, running `go mod tidy` results in a really confusing output mentioning Go 1.16 for some reason. I have no idea why / where that comes from, as I was running this w/ `go version go1.19.3 darwin/arm64` and the constraints are set to `1.17`.
```
github.com/hashicorp/syntax/builder imports
github.com/hashicorp/go-multierror loaded from …
```
> builder: bump Go to 1.19

- .github/workflows/test.yml
I'm not sure why this wasn't picked up by dependabot.
Either way, this should address the following warning
https://github.com/hashicorp/syntax/actions/runs/3656845023
> github: bump checkout job to v3

- .github/workflows/release.yml
- .github/workflows/test.yml
The intention here is to reduce the security risk posed by the supply chain - i.e. externally maintained GitHub Actions.
The expectation is that dependabot will continue to update these hashes as and when new versions become available.
> github: Pin external GitHub Actions to hashes

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- tests/snapshot/hcl/block_labels.hcl
- tests/snapshot/hcl/block_labels.hcl.snap
- tests/snapshot/hcl/block_nested_complex.hcl
- tests/snapshot/hcl/block_nested_complex.hcl.snap
Fixes #93 
Previously a block label would only be allowed to contain the set of characters in an Identifier, however a block label string literal can contain pretty much any character. This commit updates the base HCL grammar to support both identifiers and string literals in block labels and adds tests to ensure this behaviour works as expected.
* This PR also fixes up the grammar because it would match block labels that spanned lines, whereas the language spec doesn't allow that
* This PR doesn't solve the issue of a brace or a double quote being _in_ a string literal;  e.g. `blockname "foo\{" {` or `blockname "foo\"bar" {` would do weird highlighting. However, this PR is still much better at highlighting than the current code.
> Be more permissive in allowed characters in a block label

- src/terraform.yml
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/terraform/expressions_functions.tf
- tests/snapshot/terraform/expressions_functions.tf.snap
This adds support for provider defined functions (e.g. `provider::framework::example("hi")`) to the Terraform HCL syntax.
Resolves #98
> feat: support provider defined functions for Terraform HCL

- .github/workflows/add-copyright-headers.yml
The workflow is copied from https://github.com/hashicorp/terraform-ls/blob/fc7ab87b66e774b9d7579dedc51e1041fb669112/.github/workflows/add-copyright-headers.yml
> chore: add workflow to automatically add copyright headers when they are missing

- .github/workflows/pulls.yml
- .github/workflows/test.yml
This PR adds a new workflow to run on pull requests only while adjusting the existing test workflow to only run on commits on main from now on.
The following will happen on PRs now:
* `npm run build` will be run as part of a new build job
* `copywrite headers` will be run as part of the build job as well
* If there are any changes (e.g. to file headers) or to the generated syntax json files the diff will be committed as a new commit and the workflow is aborted
* If there are no changes (e.g. when running on the self-update commit after it has been made) the test job will run and decide the fate of whether the workflow fails or succeeds
This pattern is something we used over in CDKTF repositories a lot. It stems from the projen.io configuration management tool.
This change allows us to …
> feat: self update if there have been changes to the grammar but it was not built locally

- src/terraform.yml
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/terraform/expressions_functions.tf
- tests/snapshot/terraform/expressions_functions.tf.snap
This PR adds two minor fixes to the Terraform grammar for provider-defined functions:
* Add the missing `terraform` suffix to the Textmate scope
* Add an optional `core::` prefix to the built-in functions
And a couple of test cases to ensure that we don't highlight built-in functions or keywords differently when they're part of a namespaced function.
> Add optional `core` prefix to Terraform functions

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- tests/snapshot/hcl/expressions_functions.hcl
- tests/snapshot/hcl/expressions_functions.hcl.snap
This PR adds support for namespaced functions to the HCL grammar.
It is a pre-requirement for https://github.com/hashicorp/syntax/issues/35 and will allow us to release a new vscode-hcl version.
> Add support for namespaced functions to HCL grammar

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/expressions_conditional.hcl.snap
- tests/snapshot/hcl/issue79.hcl
- tests/snapshot/hcl/issue79.hcl.snap
- tests/snapshot/hcl/issue941.hcl.snap
- tests/snapshot/terraform/expressions_conditional.tf.snap
- tests/snapshot/terraform/issue941.tf.snap
This PR fixes a couple of issues related to highlighting in objects:
* `==` is now correctly detected within objects (as reported in #79)
* `:` is now correctly detected as operator (yaml typo)
* string-based object keys are correctly detected
> Improve highlighting within objects/maps

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/issue114.hcl
- tests/snapshot/hcl/issue114.hcl.snap
> Fix mis-highlight for `=>`

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- tests/snapshot/hcl/block_labels.hcl
- tests/snapshot/hcl/block_labels.hcl.snap
- tests/snapshot/hcl/issue114.hcl.snap
Looking at the screenshots from #115, I noticed that the `local` keyword was highlighted in a different way than in the current vscode-hcl grammar.
I traced this back to #94, which changed the recognition of blocks. I made this a little less permissive by disallowing `?` in block labels. This fixes the case where a ternary operator followed by an object is recognized as a block.
> Fix mis-highlight for conditionals detected as a block

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/issue113.hcl
- tests/snapshot/hcl/issue113.hcl.snap
This PR improves the inline-for regex, which used to break the highlighting of the rest of the file because it was never terminated.
In the old structure, the `end: \n` regex never matched the end of the line in the example, because the `object` repository would consume the `{` at the end of the line (including the newline). By changing this to a single `match` regex, we can now match the entire line and then delegate the second capture expression to the `for_expression_body` as before.
This shouldn't affect any of our existing tests related to `for`-expressions.
Closes #113
> Fix inline for-expression matching

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- tests/snapshot/hcl/block_labels.hcl
- tests/snapshot/hcl/block_labels.hcl.snap
This PR removes `{` as disallowed character inside block labels to fix an issue with external template strings. Since were dealing with a string here, we can allow most characters.
Closes #119
> Allow curly braces in block label strings

- .gitignore
- syntaxes/sentinel.tmGrammar.json
- tests/snapshot/sentinel/basic.sentinel.snap
- tests/snapshot/sentinel/boolean_expr.sentinel.snap
- tests/snapshot/sentinel/collections.sentinel.snap
- tests/snapshot/sentinel/comments.sentinel.snap
- tests/snapshot/sentinel/conditional.sentinel.snap
- tests/snapshot/sentinel/functions.sentinel.snap
- tests/snapshot/sentinel/imports.sentinel.snap
- tests/snapshot/sentinel/inbuilt_funcs.sentinel
- tests/snapshot/sentinel/inbuilt_funcs.sentinel.snap
- tests/snapshot/sentinel/lists.sentinel.snap
- tests/snapshot/sentinel/logging_errors.sentinel.snap
- tests/snapshot/sentinel/loops.sentinel.snap
- tests/snapshot/sentinel/maps.sentinel.snap
- tests/snapshot/sentinel/maths.sentinel.snap
- tests/snapshot/sentinel/params.sentinel.snap
- tests/snapshot/sentinel/rules.sentinel.snap
- tests/snapshot/sentinel/slices.sentinel.snap
- tests/snapshot/sentinel/undefined.sentinel.snap
- tests/snapshot/sentinel/values.sentinel.snap
- tests/snapshot/sentinel/variables.sentinel.snap
This PR updates the Sentinel Syntax Highlighting:
* Moves to an easier to understand "repository" style location for types of matches. This is similar to the TF syntax
* Updates the inbuilt function matching to NOT highlight non-function call locations e.g.
```
append(foo, bar)    <-- Highlight "append"
append = 2          <-- Do not highlight as it's not a function call
```
* Adds missing builtin function compare
* Fixes highlighting double symbol operators e.g. `==`
* Highlights triple and double word operators better e.g. `is not empty`
---
Note this PR should be squash merged
> Update sentinel syntax highlighting

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
- syntaxes/terraform.tmGrammar.json
- tests/snapshot/hcl/block_labels.hcl
- tests/snapshot/hcl/block_labels.hcl.snap
This fixes the following problem in Terraform Test files (which use the HCL syntax instead of the more specialized Terraform one):
The grammar treats the opening brace that is part of the template string as a block and therefore breaks the following lines (mostly treated as a string).
This PR restricts parsing blocks as it only allows block labels to contain any character if that label is enclosed by double quotes. If it isn't only `\w-_` are valid characters.
> (TFECO-7531) fix(hcl): don't parse expressions containing an open curly brace as blocks

- src/_main.yml
- syntaxes/hcl.tmGrammar.json
Solved #164 
<details><summary>Issue Details</summary>
I upgraded [Shiki](https://shiki.matsu.io/) version to one that came after [this](https://github.com/hashicorp/syntax/commit/cc2b4d4fe389f14b8a13937f4e0d7b2811b57588#diff-483a7704bb65e7c8a156f5990c81c83143f3e4204744d1a86616cd0fc9c452c0R85) change and It caused tabs with HCL code blocks to freeze.
It turned out there is a **"catastrophic backtracking"** in that regex because:  
`[^\S\r\n]*` could match zero characters, which makes the number of possibilities grow exponentially.
Here's a demonstration of it:
https://regex101.com/r/9vmzvg/2/debugger
I'm not sure if it can cause a DDOS on servers that highlighting with this syntax, it's not so noticeable on fast engines like Onigurama, but it's caused JS engines to be not usable like …
> Fix catastrophic backtracking of whitespaces in blocks
